<div class="form-grop spacer">
    <a type="button" href="Issue/add" class="btn btn-primary col-xs-1">Add Issue</a>
    <div class="col-xs-3 selectContainer">
        <form id="issuesPerPageForm" class="form-horizontal" action="Issue" method="post">
            <select id="issuesPerPage" name="" name="language" class="form-control" onchange="submitForm(document.getElementById('issuesPerPageForm'));">
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="20">20</option>
            </select>
        </form>
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr class="info">
            <th>Client Name</th><th>Action item/Request</th><th>Description</th><th>GH number</th><th>Priority (High, Med, Low)</th><th>Category (Bug, Enhancement, Reporting, OPS Support)</th><th>Assigned To</th><th>Comments</th><th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $row_content;?>
    </tbody>
</table>
<ul class="pager col-xs-12">
    <li class="previous disabled"><a href="#">&larr; Previous</a></li>
    <li class="next"><a href="#">Next &rarr;</a></li>
</ul>